### ISSUE TITLE
de-overload built-in Sass color and math functions

### ISSUE THREAD

**Issue by lunelson** [lunelson/homework#1]
```scss
/*
COLOR LEVEL 4
https://github.com/w3c/csswg-drafts/issues/3187#issuecomment-499126198

color / color-mod
  alpha: A value for the alpha-transparency between 0% and 100%.
  red|green|blue: A value between 0 and 255. Given a starting color of rgb(140, 254, 255), the starting red value would be 140, so anything higher than 140 increases the amount of red in the color and anything lower than 140 decreases the amount of red in color. Green and blue work the same way, with affecting their respective color.
  blackness|whiteness: A value between 0% and 100%.
  contrast: A value between 0% and 100%.
  saturation: A value between 0% and 100%. 0% is gray.
  lightness: A value between 0% and 100%. 0% is black, and 100% is white.
  tint: A value between 0% and 100%.
  hue: A value between 0 and 360.
  shade: A value between 0% and 100%. 100% is black.
  blend: Blend makes it easy to blend a color with another color.

MATH
https://twitter.com/bdc/status/1100921258839953408
  min
  max
  clamp
  sin
  cos
  tan
  acos
  asin
  atan
  atan2
  hypot
  sqrt
  pow
*/

$sass-min: get-function('min');
$sass-max: get-function('max');
$sass-clamp: get-function('clamp');
$sass-sin: get-function('sin');
$sass-cos: get-function('cos');
$sass-tan: get-function('tan');
$sass-acos: get-function('acos');
$sass-asin: get-function('asin');
$sass-atan: get-function('atan');
$sass-atan2: get-function('atan2');
$sass-hypot: get-function('hypot');
$sass-sqrt: get-function('sqrt');
$sass-pow: get-function('pow');

@function --min($args...) { @return call($sass-min, $args...); }
@function --max($args...) { @return call($sass-max, $args...); }
@function --clamp($args...) { @return call($sass-clamp, $args...); }
@function --sin($args...) { @return call($sass-sin, $args...); }
@function --cos($args...) { @return call($sass-cos, $args...); }
@function --tan($args...) { @return call($sass-tan, $args...); }
@function --acos($args...) { @return call($sass-acos, $args...); }
@function --asin($args...) { @return call($sass-asin, $args...); }
@function --atan($args...) { @return call($sass-atan, $args...); }
@function --atan2($args...) { @return call($sass-atan2, $args...); }
@function --hypot($args...) { @return call($sass-hypot, $args...); }
@function --sqrt($args...) { @return call($sass-sqrt, $args...); }
@function --pow($args...) { @return call($sass-pow, $args...); }

@function min($args...) { @return #{'min(#{$args})'}; }
@function max($args...) { @return #{'max(#{$args})'}; }
@function clamp($args...) { @return #{'clamp(#{$args})'}; }
@function sin($args...) { @return #{'sin(#{$args})'}; }
@function cos($args...) { @return #{'cos(#{$args})'}; }
@function tan($args...) { @return #{'tan(#{$args})'}; }
@function acos($args...) { @return #{'acos(#{$args})'}; }
@function asin($args...) { @return #{'asin(#{$args})'}; }
@function atan($args...) { @return #{'atan(#{$args})'}; }
@function atan2($args...) { @return #{'atan2(#{$args})'}; }
@function hypot($args...) { @return #{'hypot(#{$args})'}; }
@function sqrt($args...) { @return #{'sqrt(#{$args})'}; }
@function pow($args...) { @return #{'pow(#{$args})'}; }
```
